### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#13]
Clean code is easier to understand and contribute to. I see some unused imports in the code

Please remove unused imports. I would also suggest using a linter to report these issues automatically or autoflake8 to automatically remove them.

![image](https://user-images.githubusercontent.com/42288570/182011775-ab80a42f-527f-415b-b0f8-f1bce311d168.png)

**Comment by jmosbacher** [comment]
Done. Thanks!
