### ISSUE TITLE
Make editors and linters not complain about unused imports

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#14]
It is friction that editors and linters will complain about unused imports

![image](https://user-images.githubusercontent.com/42288570/182012026-1f12a68d-1f01-4461-aa5a-8a87bc044a07.png)
![image](https://user-images.githubusercontent.com/42288570/182012139-012d68d4-9987-4392-98bd-0bdaf976bc90.png)

The solution could be as simple as adding some disabling comment like `# noqa` to the documentation. But unfortunately `# noqa` does not work for pylint and pyright. Some solution that works across linters and editors would be nice.

Maybe the import should be different. Like for example?

```python
import pydantic_panel as pp
pp.extension()
```

**Comment by MarcSkovMadsen** [comment]
Another solution could be to support, document or even favor using

```python
from pydantic_panel import Pydantic
Pydantic(SomePydanticModel)
```

**Comment by jmosbacher** [comment]
I really like this idea
```python
import pydantic_panel as pp
pp.extension()
```
as it will also allow us to take in some options to configure the behavior of these extensions.
I think I will implement this very soon.
