### ISSUE TITLE
Extend elevator pitch a bit

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#6]
The current Github about says

![image](https://user-images.githubusercontent.com/42288570/181937154-0b7b7ec9-f082-4abd-8872-eb0c134412ea.png)

I believe this package will not only enable users to edit Pydantic Models but also build data apps on top of Pydantic Models.

**Comment by MarcSkovMadsen** [comment]
## Suggested new about

Edit Pydantic models and build data apps from Pydantic models using the awesome Panel package.

**Comment by jmosbacher** [comment]
Done. Thanks
