### ISSUE TITLE
Provide developer instructions

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#8]
Developer instructions would help me and others contribute.

I would need to know

- How to install for development
- How to "build" and test
- The style guide (or automated checks used)

## Example

I can see this project uses Poetry. I'm not familiar with poetry. I normally use pyproject.toml+setup.cfg+setup.py and can do `pip install -e .`. What would I do here to install for development?

**Comment by jmosbacher** [comment]
Solved by updating pip.
