### ISSUE TITLE
Make it ok to use the Pydantic pane directly

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jmosbacher/pydantic-panel#9]
## Request

Remove *This pane is not expected to be used directly* from `Pydantic` docstring.

## Motivation

I love the fact that you support using `pn.panel(model)`. But I don't see any reasons why I could not use `Pydantic(model)` directly. And sometimes it can be better to be very explicit about which Pane you use.

![image](https://user-images.githubusercontent.com/42288570/182011169-f6419337-e534-4d9b-96c1-eda69847e75a.png)

**Comment by MarcSkovMadsen** [comment]
An added benefit is also that you can get specific help if good docstrings like below are added

![image](https://user-images.githubusercontent.com/42288570/182012306-d40fd365-3781-4f9d-a163-a08342bb70ce.png)

**Comment by jmosbacher** [comment]
Good point.

**Comment by jmosbacher** [comment]
Fixed in #16
